# render.yaml
services:
  - type: web
    name: tu-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT 'app:create_app()'"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: afiliados_db
          property: connectionString