# Archivo: render.yaml
services:
  - type: web
    name: afiliado_online
    env: python
    buildCommand: ""
    startCommand: gunicorn app:create_app()
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: afiliados_db
          property: connectionString